import = [
    "~/.config/alacritty/themes/themes/gruvbox_dark.toml",
]

[env]
TERM = "xterm-256color"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
startup_mode = "Fullscreen"
option_as_alt = "Both"

[window.padding]
x = 5
y = 5
