import = [
    "~/.config/alacritty/active.toml", # Dynamically configure Alacritty's theme.
]

[env]
TERM = "xterm-256color"
ALACRITTY = "true"

[font]
size = 13.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
option_as_alt = "Both"
